### PR TITLE
Method chaining

### LINKED ISSUE #20: request method chaining for setters
Hi,

Would it be interesting to add method chaining for set methods? For example, if consider [dateTimeValue](https://github.com/outlook/vobject-js/blob/master/lib/vobject/dateTimeValue.js) it may look the following:
```js
var dateTimeValue = vobject.dateTimeValue();
dateTimeValue.parseTimestamp(timestamp).setTZID(tzid);
```

### PR DESCRIPTION
**Pull request by killmenot**
Hi,

Based on our discussion in #20. In additional, I lock packages version and fix nsp running. Take a look

closes #20

### CODE REVIEW

**Comment by pierre-elie** [comment]
I thought you were not using `this` 😄  https://github.com/outlook/vobject-js/issues/20#issuecomment-218753908

**Comment by killmenot** [comment]
Do you prefer to see explicit `return this` ?

I decided to provide `return this` to component class and then re use it in inherited  classes

**Comment by pierre-elie** [comment]
No, that’s fine, thanks a lot @killmenot!
Will publish update asap

**Comment by killmenot** [comment]
Thank you for the lib. It's the best one I found on npm

**Pull request merged**
